### ISSUE TITLE
Argument 2 passed to Packagist\Api\Result\Factory::createResult() must be of the type array, null given

### ISSUE THREAD

**Issue by Soullivaneuh** [KnpLabs/packagist-api#47]
When trying to do:

```php
$package = $this->packagistClient->get('sonata-project/classification-media-bundle');
```

I get:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Packagist\Api\Result\Factory::createResult() must be of the type array, null given, called in /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Result/Factory.php on line 81 and defined in /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Result/Factory.php:103
Stack trace:
#0 /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Result/Factory.php(81): Packagist\Api\Result\Factory->createResult('Packagist\\Api\\R...', NULL)
#1 /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Result/Factory.php(29): Packagist\Api\Result\Factory->createPackageResults(Array)
#2 /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Client.php(219): Packagist\Api\Result\Factory->create(Array)
#3 /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/kn in /home/sullivan/projects/fork/sonata-project/dev-kit/vendor/knplabs/packagist-api/src/Packagist/Api/Result/Factory.php on line 103
```

Only on this package so far.

Ref: https://packagist.org/packages/sonata-project/classification-media-bundle

Using last stable v1.5.0

**Comment by kmadejski** [comment]
I confirm. Moreover, the problem exists for many other packages, just for example: `netgen/ez-forms-bundle` or `eab/image-filter-bundle`.

**Comment by kmadejski** [comment]
Sorry @Soullivaneuh, I have no idea why I didn't notice your PR. Closed mine in favour of yours.
